---
 ##
 # Demo playbook to install IIS, .NET Core dependencies, create a sample web app, and finally host that app via IIS
 #

- name: Full Ansible demo for Rev
  hosts: winserv1
  gather_facts: no
  vars:
    temp_dir: C:\Users\Administrator\Downloads
    netcoresdk_exe: "{{ temp_dir }}\\netcoresdk22.exe"
    netcoresdk_log: "{{ temp_dir }}\\netcoresdk22_log.txt"
    netcoresdk_url: https://download.visualstudio.microsoft.com/download/pr/28431bba-e071-4e98-86a9-aa7e0c9050fc/0677f2fd79faee65f5d48260b9f303e5/aspnetcore-runtime-6.0.15-win-x64.exe
    netcorehost_exe: "{{ temp_dir }}\\netcorehost22.exe"
    netcorehost_log: "{{ temp_dir }}\\netcorehost22_log.txt"
    netcorehost_url: https://download.visualstudio.microsoft.com/download/pr/e38901ef-e9ac-4331-a6aa-f2aec3b1754b/6d695fa51a4960393edaf725ce970a86/dotnet-hosting-6.0.15-win.exe
    website_parent_dir: C:\sites\example
    website_publish_dir: "{{ website_parent_dir }}\\app"
    website_temp_dir: "{{ website_parent_dir }}\\tmp"
  tasks:

    # IIS installation and configuration

    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: True
        include_management_tools: True
      register: win_feature
    
    - name: Remove Default IIS website and site binding
      win_iis_website:
        name: "Default Web Site"
        state: absent

    # .NET Core SDK installation

    - name: Download Microsoft .NET Core 6.0 SDK installer
      win_get_url:
        url: "{{ netcoresdk_url }}"
        dest: "{{ netcoresdk_exe }}"

    - name: Run Microsoft .NET Core 6.0 SDK installer
      raw: "{{ netcoresdk_exe }} /quiet /log {{ netcoresdk_log }}"

    - name: Clean up downloaded files
      win_file:
        path: "{{ netcoresdk_exe }}"
        state: absent

    # .NET Core Hosting Bundle installation

    - name: Download Microsoft .NET Core 2.2 hosting bundle installer
      win_get_url:
        url: "{{ netcorehost_url }}"
        dest: "{{ netcorehost_exe }}"

    - name: Stop IIS
      win_shell: iisreset /STOP

    - name: Run Microsoft .NET Core 2.2 hosting bundle installer
      raw: "{{ netcorehost_exe }} /passive /AcceptEULA /log {{ netcorehost_log }}"

    - name: Start IIS
      win_shell: iisreset /START

    - name: Clean up downloaded files
      win_file:
        path: "{{ netcorehost_exe }}"
        state: absent

    # Create example .NET Core web app and related IIS app pool

    - name: Create web app directory
      win_file:
        path: "{{ website_temp_dir }}"
        state: directory

    - name: Create sample web app
      win_shell: dotnet new webapp; dotnet publish --output {{ website_publish_dir }}
      args:
        chdir: "{{ website_temp_dir }}"
        creates: Program.cs

    - name: Create sample web app Application Pool
      win_iis_webapppool:
        name: SampleAppPool
        state: started
        attributes:
          enable32BitAppOnWin64: False
          managedRuntimeVersion: null

    - name: Add IIS_IUSRS to sample app directory
      win_acl:
        path: "{{ website_publish_dir }}"
        user: IIS_IUSRS
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'None'

    - name: Add IIS APPPOOL\SampleAppPool to sample app directory
      win_acl:
        path: "{{ website_parent_dir }}"
        user: IIS APPPOOL\SampleAppPool
        rights: FullControl
        type: allow
        state: present
        inherit: ContainerInherit, ObjectInherit
        propagation: 'None'

    - name: Create sample IIS web app
      win_iis_website:
        name: Sample App
        state: started
        port: 80
        ip: 18.141.201.24
        application_pool: SampleAppPool
        physical_path: "{{ website_publish_dir }}"
        parameters: logfile.directory:{{ website_parent_dir }}\logs
      register: website
